apiVersion: v1
kind: ConfigMap
metadata:
  name: init-script-configmap
data:
  init-script.sh: |
    #!/bin/bash
    DESTINATION="zephyr-7b-beta.Q8_0.gguf"
    MODEL_URL="https://huggingface.co/TheBloke/zephyr-7B-beta-GGUF/resolve/main/zephyr-7b-beta.Q8_0.gguf"
    sudo mkdir -p "$(dirname "$DESTINATION")"
    sudo curl -o "$DESTINATION" "$MODEL_URL"
    if [ $? -eq 0 ]; then
      echo "Modèle téléchargé avec succès dans $DESTINATION"
    else
        echo "Échec du téléchargement du modèle"
        exit 1
    fi
